version: '3.8'

services:
  tradestream:
    build: .
    container_name: tradestream-bot
    restart: unless-stopped
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./data:/app/data
      - ./logs:/app/logs
      - ./backups:/app/backups
    environment:
      - PYTHONPATH=/app/src
      - PYTHONUNBUFFERED=1
    # Uncomment if you need to expose monitoring port
    # ports:
    #   - "8080:8080"
    
    # Resource limits (adjust based on your needs)
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    
    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.path.append('src'); from health_monitor import HealthMonitor; print('healthy')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Optional: Add monitoring services
  # watchtower:
  #   image: containrrr/watchtower
  #   container_name: watchtower
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   command: --interval 300 --cleanup
  #   restart: unless-stopped
